// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run against DIRECT_URL when it is set, falling back to the
    // app's pooled connection. On Neon, DATABASE_URL points at the `-pooler`
    // endpoint (PgBouncer): fine for queries, unreliable for DDL and advisory
    // locks. DIRECT_URL should be the same database without `-pooler`.
    // Point it at a Neon branch to rehearse a migration off production.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
